# Generated by Django 5.0.6 on 2024-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preparation_steps', models.TextField(verbose_name='Шаги приготовления')),
                ('preparation_time', models.PositiveIntegerField(verbose_name='Время приготовления (в минутах)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe_images', verbose_name='Изображение')),
                ('author', models.CharField(max_length=128, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
