# Generated by Django 5.0.6 on 2024-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0007_alter_recipeingredient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='categories',
            field=models.ManyToManyField(to='cocktail.category', verbose_name='Категория'),
        ),
    ]
